// Writes src/lastmod.ts: path -> date of the last commit that changed that page, for the sitemap's <lastmod>.
// Runs before every deploy (predeploy) so crawlers get honest "changed on" hints instead of none.
import { execFileSync } from "node:child_process";
import { readdirSync, existsSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dateOf = (file) => {
  try { return execFileSync("git", ["log", "-1", "--format=%cs", "--", file], { cwd: root }).toString().trim() || null; } catch (e) { return null; }
};

const out = {};
const home = dateOf("public/index.html"); if (home) out["/"] = home;
for (const d of readdirSync(join(root, "public"), { withFileTypes: true })) {
  if (!d.isDirectory()) continue;
  const f = `public/${d.name}/index.html`;
  if (!existsSync(join(root, f))) continue;
  const date = dateOf(f);
  if (date) out[`/${d.name}/`] = date;
}
const sorted = Object.fromEntries(Object.entries(out).sort(([a], [b]) => a.localeCompare(b)));
writeFileSync(join(root, "src/lastmod.ts"), `// Generated by scripts/gen-lastmod.mjs — do not edit.\nexport const LASTMOD: Record<string, string> = ${JSON.stringify(sorted, null, 2)};\n`);
console.log(`lastmod: ${Object.keys(sorted).length} pages`);
