// GENERATED by scripts/gen-subject-units.mjs -- do not hand-edit.
// Mirrors public/shared/unit-titles.js so the Worker can look up unit
// display names server-side (e.g. for the study-group weak-spots aggregate)
// without importing client JS into the src/**/*.ts build.
export const SUBJECT_UNIT_NAMES: Record<string, Record<string, string>> = {
  "geometry": {
    "1": "Foundations: Points, Lines & Angles",
    "2": "Parallel Lines & Transversals",
    "3": "Triangles: Angles & Inequalities",
    "4": "Congruent Triangles & Proofs",
    "5": "Similarity & Proportions",
    "6": "Right Triangles & Trigonometry",
    "7": "Polygons & Quadrilaterals",
    "8": "Circles",
    "9": "Coordinate Geometry",
    "10": "Transformations & Constructions",
    "11": "3D Solids: Surface Area, Volume & Density"
  },
  "chemistry": {
    "1": "Matter & Change",
    "2": "Measurements & Math",
    "3": "Atomic Concepts",
    "4": "Periodic Table",
    "5": "Chemical Bonding",
    "6": "Chemical Quantities",
    "7": "Chemical Reactions",
    "8": "Phases of Matter",
    "9": "Gas Laws",
    "10": "Solutions",
    "11": "Thermochemistry",
    "12": "Equilibrium & Kinetics",
    "13": "Acids, Bases & Salts",
    "14": "Redox & Electrochemistry",
    "15": "Nuclear Chemistry",
    "16": "Organic Chemistry"
  },
  "algebra1": {
    "1": "Solving Equations & Inequalities",
    "2": "Linear Functions & Graphing",
    "3": "Systems of Equations & Inequalities",
    "4": "Exponents & Polynomials",
    "5": "Factoring",
    "6": "Quadratic Equations & Functions",
    "7": "Radicals & Rational Exponents",
    "8": "Exponential Functions & Sequences",
    "9": "Statistics: Data & Distributions",
    "10": "Statistics: Regression & Correlation",
    "11": "Functions: Notation, Domain/Range & Transformations"
  },
  "algebra2": {
    "1": "Polynomial Functions & Operations",
    "2": "Rational Expressions & Equations",
    "3": "Radicals & Rational Exponents",
    "4": "Exponential & Logarithmic Functions",
    "5": "Sequences & Series",
    "6": "Trigonometric Functions & the Unit Circle",
    "7": "Trigonometric Graphs & Identities",
    "8": "Complex Numbers & Quadratics Revisited",
    "9": "Function Operations, Inverses & Transformations",
    "10": "Statistics: Sampling & Inference",
    "11": "Probability",
    "12": "Subsets of Real Numbers",
    "13": "Linear Inequalities & Set-Builder and Interval Notation",
    "14": "Compound Inequalities"
  },
  "aplang": {
    "1": "The Rhetorical Situation",
    "2": "Rhetorical Appeals & Logical Fallacies",
    "3": "Rhetorical Devices & Figurative Language",
    "4": "Style: Diction, Syntax & Tone",
    "5": "Claims, Evidence & Commentary",
    "6": "Organization, Structure & Counterargument",
    "7": "The Synthesis Essay"
  },
  "globalhistory": {
    "1": "Early River Valley Civilizations",
    "2": "Classical Greece & Rome",
    "3": "Classical China & India",
    "4": "The Rise and Spread of Islam",
    "5": "Medieval Europe & the Byzantine Empire",
    "6": "Trade Networks: Silk Roads, Trans-Saharan & Indian Ocean",
    "7": "The Renaissance & Reformation",
    "8": "Age of Exploration & the Columbian Exchange",
    "9": "Absolutism & the Enlightenment",
    "10": "Age of Revolutions",
    "11": "Industrialization & Imperialism",
    "12": "World War I & the Interwar Period",
    "13": "World War II & the Holocaust",
    "14": "The Cold War, Decolonization & a Changing World"
  },
  "apbiology": {
    "1": "Chemistry of Life",
    "2": "Cell Structure & Function",
    "3": "Cellular Energetics",
    "4": "Cell Communication & Cell Cycle",
    "5": "Heredity",
    "6": "Gene Expression & Regulation",
    "7": "Natural Selection",
    "8": "Ecology"
  },
  "apush": {
    "1": "Period 1: 1491-1607",
    "2": "Period 2: 1607-1754",
    "3": "Period 3: 1754-1800",
    "4": "Period 4: 1800-1848",
    "5": "Period 5: 1844-1877",
    "6": "Period 6: 1865-1898",
    "7": "Period 7: 1890-1945",
    "8": "Period 8: 1945-1980",
    "9": "Period 9: 1980-present"
  },
  "us-history": {
    "1": "Colonization & the Atlantic World (1491-1690)",
    "2": "Colonial Society & the Road to Revolution (1690-1763)",
    "3": "Revolution & the Founding (1763-1815)",
    "4": "Expansion, Reform & Jacksonian Democracy (1815-1848)",
    "5": "Sectional Crisis & Civil War (1848-1865)",
    "6": "Reconstruction (1865-1877)",
    "7": "Industrialization & the Gilded Age (1877-1900)",
    "8": "Progressivism & Imperialism (1890-1917)",
    "9": "World War I, the 1920s & the Great Depression (1914-1939)",
    "10": "World War II & the Cold War (1939-1980)",
    "11": "Modern America (1980-Present)"
  },
  "physics": {
    "1": "Kinematics",
    "2": "Newton's Laws & Dynamics",
    "3": "Momentum & Energy",
    "4": "Circular Motion & Gravitation",
    "5": "Waves & Sound",
    "6": "Electricity",
    "7": "Magnetism & Electromagnetism",
    "8": "Optics",
    "9": "Modern Physics"
  },
  "biology": {
    "1": "Characteristics of Life & the Scientific Method",
    "2": "Chemistry of Life",
    "3": "Cell Biology",
    "4": "Energy in Cells",
    "5": "Genetics & Heredity",
    "6": "Evolution",
    "7": "Ecology",
    "8": "Human Body Systems"
  },
  "precalc": {
    "1": "Functions & Their Graphs",
    "2": "Polynomial & Rational Functions",
    "3": "Exponential & Logarithmic Functions",
    "4": "Trigonometric Functions",
    "5": "Trigonometric Identities & Equations",
    "6": "Analytic Trigonometry & Applications",
    "7": "Systems & Matrices",
    "8": "Sequences, Series & Conics",
    "9": "Limits & Intro to Calculus Concepts"
  },
  "act-prep": {
    "1": "English Section Tactics",
    "2": "Math Section Tactics",
    "3": "Reading Speed Strategies",
    "4": "Science Reasoning",
    "5": "Writing (Optional) Overview",
    "6": "Timing Frameworks",
    "7": "Question Type Patterns",
    "8": "Full Practice Workflow"
  },
  "anatomy": {
    "1": "Intro & Terminology",
    "2": "Skeletal System",
    "3": "Muscular System",
    "4": "Nervous System",
    "5": "Circulatory & Respiratory",
    "6": "Digestive & Excretory",
    "7": "Endocrine & Immune",
    "8": "Reproductive & Homeostasis"
  },
  "ap-chemistry": {
    "1": "Atomic Structure & Moles",
    "2": "Stoichiometry",
    "3": "Gas Laws",
    "4": "Thermochemistry",
    "5": "Atomic Structure & Periodicity",
    "6": "Bonding & IMFs",
    "7": "Kinetics & Equilibrium",
    "8": "Acids-Bases & Electrochemistry"
  },
  "ap-csa": {
    "1": "Java Basics & Primitive Types",
    "2": "Objects & Classes",
    "3": "Boolean Logic & Ifs",
    "4": "Iteration Loops",
    "5": "Arrays",
    "6": "ArrayLists & References",
    "7": "2D Arrays & Inheritance",
    "8": "Recursion & Algorithms"
  },
  "ap-euro": {
    "1": "Renaissance & Exploration",
    "2": "Reformation & Wars of Religion",
    "3": "Absolutism & Constitutionalism",
    "4": "Scientific Revolution & Enlightenment",
    "5": "French Revolution & Napoleon",
    "6": "Industrialization & Isms",
    "7": "WWI & Interwar Period",
    "8": "WWII & Modern Europe"
  },
  "ap-macro": {
    "1": "Basic Economic Concepts",
    "2": "Economic Indicators & GDP",
    "3": "Unemployment & Inflation",
    "4": "AD-AS Model",
    "5": "Fiscal Policy",
    "6": "Money, Banking & Fed",
    "7": "Monetary Policy",
    "8": "International Trade & FOREX"
  },
  "ap-micro": {
    "1": "Basic Concepts & Trade",
    "2": "Supply & Demand Deep Dive",
    "3": "Elasticity",
    "4": "Consumer Choice",
    "5": "Production & Costs",
    "6": "Market Structures",
    "7": "Factor Markets",
    "8": "Government Intervention & Failures"
  },
  "ap-physics": {
    "1": "Kinematics",
    "2": "Dynamics & Newton's Laws",
    "3": "Energy & Work",
    "4": "Momentum",
    "5": "Circular Motion & Gravity",
    "6": "Rotational Motion",
    "7": "Waves & Sound",
    "8": "Electrostatics & Circuits"
  },
  "ap-psych": {
    "1": "History & Research Methods",
    "2": "Biological Bases",
    "3": "Sensation & Perception",
    "4": "Learning",
    "5": "Cognition & Memory",
    "6": "Motivation, Emotion & Development",
    "7": "Personality & Testing",
    "8": "Disorders & Social Psych"
  },
  "ap-stats": {
    "1": "Exploring Data",
    "2": "Modeling Distributions",
    "3": "Describing Bivariate Data",
    "4": "Designing Studies",
    "5": "Probability & Simulation",
    "6": "Random Variables",
    "7": "Sampling Distributions",
    "8": "Inference: Confidence & Tests"
  },
  "ap-usgov": {
    "1": "Foundations of Democracy",
    "2": "Branches: Legislative",
    "3": "Branches: Executive & Bureaucracy",
    "4": "Judicial Branch & Courts",
    "5": "Civil Liberties & Rights",
    "6": "Political Ideologies & Beliefs",
    "7": "Voting, Elections & Media",
    "8": "Interest Groups & Policy Making"
  },
  "ap-world": {
    "1": "The Global Tapestry 1200-1450",
    "2": "Networks of Exchange",
    "3": "Land-Based Empires",
    "4": "Transoceanic Connections 1450-1750",
    "5": "Revolutions 1750-1900",
    "6": "Imperialism & Migration",
    "7": "Global Conflict 1900-present",
    "8": "Cold War & Decolonization"
  },
  "ap-human-geography": {
    "1": "Thinking Geographically",
    "2": "Population & Migration",
    "3": "Cultural Patterns & Processes",
    "4": "Political Patterns & Processes",
    "5": "Agriculture & Rural Land Use",
    "6": "Cities & Urban Land Use",
    "7": "Industrialization & Economic Development"
  },
  "art-history": {
    "1": "Art Vocabulary & Analysis",
    "2": "Ancient & Classical Art",
    "3": "Medieval & Renaissance",
    "4": "Baroque & Rococo",
    "5": "19th Century Movements",
    "6": "Modern Art Revolution",
    "7": "Global Traditions",
    "8": "Contemporary Art & Critique"
  },
  "astronomy": {
    "1": "Observing the Sky",
    "2": "Earth-Moon-Sun System",
    "3": "Solar System Survey",
    "4": "Telescopes & Light",
    "5": "Stars & Their Lives",
    "6": "Galaxies & Cosmology",
    "7": "Space Exploration History",
    "8": "Exoplanets & the Search for Life"
  },
  "computer-science": {
    "1": "Computing Basics & Binary",
    "2": "Programming Fundamentals",
    "3": "Control Flow & Functions",
    "4": "Data Structures Intro",
    "5": "Algorithms & Problem Solving",
    "6": "Web & Internet How It Works",
    "7": "Data & Privacy",
    "8": "Ethics & Careers"
  },
  "creative-writing": {
    "1": "Writer's Toolkit & Habits",
    "2": "Story Elements Deep Dive",
    "3": "Character Craft",
    "4": "Dialogue That Works",
    "5": "Point of View Choices",
    "6": "Poetry Forms & Imagery",
    "7": "Revision as Rewriting",
    "8": "Workshop: Giving & Taking Feedback"
  },
  "earth-science": {
    "1": "Earth Systems & Scientific Method",
    "2": "Plate Tectonics",
    "3": "Earthquakes & Volcanoes",
    "4": "Minerals & Rocks",
    "5": "Weathering, Erosion & Geologic Time",
    "6": "Atmosphere & Weather",
    "7": "Climate & Climate Change",
    "8": "Astronomy: Earth-Moon-Sun & Solar System"
  },
  "economics": {
    "1": "Scarcity & Opportunity Cost",
    "2": "Supply & Demand",
    "3": "Market Structures",
    "4": "Business Organizations & Labor",
    "5": "Money, Banking & the Fed",
    "6": "Personal Finance",
    "7": "Government & the Economy",
    "8": "International Trade & Globalization"
  },
  "english-10": {
    "1": "World Literature & Cultural Context",
    "2": "Rhetorical Analysis",
    "3": "Shakespearean Drama & Tragedy",
    "4": "Dystopian Literature & Allegory",
    "5": "Argumentation & Logical Fallacies",
    "6": "Poetry Analysis II",
    "7": "Research & Citation (MLA)",
    "8": "Style & Syntax"
  },
  "english-9": {
    "1": "Elements of Story",
    "2": "Figurative Language & Literary Devices",
    "3": "Symbolism, Theme & Motif",
    "4": "Poetry Essentials",
    "5": "The Epic & The Odyssey",
    "6": "Rhetoric & Persuasion",
    "7": "Grammar & Mechanics Essentials",
    "8": "Writing: Thesis, Evidence & Paragraph Craft"
  },
  "environmental-science": {
    "1": "Ecosystems & Energy Flow",
    "2": "Biodiversity & Populations",
    "3": "Water Resources",
    "4": "Land Use & Agriculture",
    "5": "Energy Resources",
    "6": "Pollution Types",
    "7": "Climate Systems",
    "8": "Policy & Solutions"
  },
  "french-1": {
    "1": "Greetings & Alphabet",
    "2": "Articles & Nouns",
    "3": "Regular -ER Verbs",
    "4": "Être, Avoir & Questions",
    "5": "Adjectives & Description",
    "6": "Family & Possession",
    "7": "Food & Café Culture",
    "8": "City Places & Directions"
  },
  "geography": {
    "1": "Map Skills & Tools",
    "2": "Physical Geography & Landforms",
    "3": "Climate & Biomes",
    "4": "Population & Migration",
    "5": "Culture & Language",
    "6": "Economic Geography",
    "7": "Political Geography",
    "8": "Urban & Environmental Issues"
  },
  "german-1": {
    "1": "Greetings & Pronunciation",
    "2": "Articles & Cases Intro",
    "3": "Regular Verbs",
    "4": "Sein & Haben",
    "5": "Word Order Basics",
    "6": "Family & Descriptions",
    "7": "Food & Shopping",
    "8": "Daily Routine & Time"
  },
  "health": {
    "1": "Mental & Emotional Health",
    "2": "Nutrition & Physical Fitness",
    "3": "Substance Abuse Prevention",
    "4": "Human Development",
    "5": "Injury Prevention & Safety",
    "6": "Disease Prevention",
    "7": "Consumer & Community Health",
    "8": "Healthy Relationships"
  },
  "journalism": {
    "1": "What Makes News",
    "2": "News Writing & Inverted Pyramid",
    "3": "Interviewing Skills",
    "4": "Fact-Checking & Ethics",
    "5": "Feature Writing",
    "6": "Opinion vs News",
    "7": "Media Law Basics",
    "8": "Digital Storytelling"
  },
  "music-theory": {
    "1": "Notes, Staff & Clefs",
    "2": "Rhythm & Meter",
    "3": "Scales & Keys",
    "4": "Intervals",
    "5": "Chords & Harmony",
    "6": "Song Form & Structure",
    "7": "Ear Training Basics",
    "8": "Analysis & Composition Starter"
  },
  "psychology": {
    "1": "History & Approaches",
    "2": "Research Methods",
    "3": "Biological Bases of Behavior",
    "4": "Sensation & Perception",
    "5": "Learning & Memory",
    "6": "Development",
    "7": "Personality Theories",
    "8": "Social Psychology & Disorders"
  },
  "sat-math": {
    "1": "Heart of Algebra",
    "2": "Problem Solving & Data",
    "3": "Passport to Advanced Math",
    "4": "Geometry Essentials",
    "5": "Trigonometry Basics",
    "6": "Calculator Strategies",
    "7": "No-Calculator Tactics",
    "8": "Timing & Pacing Drills"
  },
  "sat-reading": {
    "1": "Information & Ideas",
    "2": "Command of Evidence",
    "3": "Words in Context",
    "4": "Expression of Ideas",
    "5": "Standard English Conventions",
    "6": "Science Passages",
    "7": "History/Social Studies Passages",
    "8": "Pacing & Strategy"
  },
  "sociology": {
    "1": "Sociological Perspective",
    "2": "Research Methods",
    "3": "Culture & Socialization",
    "4": "Social Structure & Groups",
    "5": "Deviance & Stratification",
    "6": "Race, Gender & Inequality",
    "7": "Family & Religion",
    "8": "Social Change & Movements"
  },
  "spanish-1": {
    "1": "Greetings & Introductions",
    "2": "Numbers, Dates & Time",
    "3": "Family & Descriptions",
    "4": "School & -AR Verbs",
    "5": "Food & -ER/-IR Verbs",
    "6": "Gustar & Likes",
    "7": "Stem-Changers & Clothing",
    "8": "House & Ser vs Estar"
  },
  "spanish-2": {
    "1": "Preterite Introduction",
    "2": "Preterite vs Imperfect",
    "3": "Commands",
    "4": "Direct & Indirect Object Pronouns",
    "5": "Reflexives & Daily Routine",
    "6": "Future & Conditional",
    "7": "Present Subjunctive",
    "8": "Travel, Health & Culture"
  },
  "spanish-3": {
    "1": "Advanced Preterite vs Imperfect",
    "2": "Future & Conditional",
    "3": "Present Perfect",
    "4": "Commands Review & Advanced",
    "5": "Subjunctive Deep Dive",
    "6": "Por vs Para & Prepositions",
    "7": "Culture: Spanish-Speaking World",
    "8": "Reading & Listening Strategies"
  },
  "speech-debate": {
    "1": "Public Speaking Foundations",
    "2": "Speech Organization",
    "3": "Delivery & Body Language",
    "4": "Argument Construction",
    "5": "Evidence & Research",
    "6": "Resolution Analysis",
    "7": "Refutation & Crossfire",
    "8": "Event Formats (CX, LD, PF)"
  },
  "statistics": {
    "1": "Describing Data & Graphs",
    "2": "Distributions & Normal Curve",
    "3": "Correlation vs Causation",
    "4": "Sampling & Study Design",
    "5": "Probability Basics",
    "6": "Confidence Intervals",
    "7": "Hypothesis Testing Logic",
    "8": "Misleading Statistics in the Wild"
  },
  "study-skills": {
    "1": "How Memory Works",
    "2": "Active Recall & Spaced Repetition",
    "3": "Note-Taking Systems",
    "4": "Time Management",
    "5": "Reading Textbooks Efficiently",
    "6": "Test-Taking Strategies",
    "7": "Focus & Distraction Management",
    "8": "Goal Setting & Habits"
  },
  "us-government": {
    "1": "Foundations of American Democracy",
    "2": "The Constitution: Principles & Structure",
    "3": "Congress",
    "4": "The Presidency",
    "5": "The Judiciary",
    "6": "Civil Liberties & Civil Rights",
    "7": "Political Participation: Elections & Media",
    "8": "The Bureaucracy & Policy Making"
  },
  "world-history": {
    "1": "Ancient Civilizations",
    "2": "Classical Greece & Rome",
    "3": "Post-Classical Asia & Africa",
    "4": "Medieval Europe",
    "5": "Renaissance & Reformation",
    "6": "Age of Exploration",
    "7": "Revolutions & Enlightenment",
    "8": "Industrial Age & World Wars"
  },
  "calculus": {
    "1": "Limits & Continuity",
    "2": "Derivative Rules & Techniques",
    "3": "Applications of Derivatives",
    "4": "Integration Basics",
    "5": "Applications of Integrals",
    "6": "Exponential & Logarithmic Calculus",
    "7": "Related Rates & Optimization",
    "8": "Sequences & Series Intro"
  },
  "calc-ab": {
    "1": "Limits & Continuity",
    "2": "Differentiation: Definition & Basic Rules",
    "3": "Differentiation: Composite, Implicit & Inverse",
    "4": "Contextual Applications of Differentiation",
    "5": "Analytical Applications of Differentiation",
    "6": "Integration & Accumulation of Change",
    "7": "Differential Equations",
    "8": "Applications of Integration"
  },
  "calc-bc": {
    "1": "Limits & Continuity",
    "2": "Differentiation & Applications",
    "3": "Integration & Differential Equations",
    "4": "Applications of Integration",
    "5": "Parametric, Polar & Vector Functions",
    "6": "Infinite Sequences & Series",
    "7": "Taylor & Maclaurin Series",
    "8": "Polynomial Approximations & Series Convergence"
  }
};
