// Generated by scripts/generate-tips.mjs, do not edit.
export const TIPS: { slug: string; published: string }[] = [
  {
    "slug": "chain-rule",
    "published": "2026-10-04"
  },
  {
    "slug": "comma-splice-fanboys",
    "published": "2026-10-04"
  },
  {
    "slug": "exponent-rules",
    "published": "2026-10-04"
  },
  {
    "slug": "factoring-trinomials",
    "published": "2026-10-04"
  },
  {
    "slug": "ionic-vs-covalent-bonds",
    "published": "2026-10-04"
  },
  {
    "slug": "kinematics-equations",
    "published": "2026-10-04"
  },
  {
    "slug": "law-of-sines-vs-cosines",
    "published": "2026-10-04"
  },
  {
    "slug": "limiting-reagent",
    "published": "2026-10-04"
  },
  {
    "slug": "mitosis-vs-meiosis",
    "published": "2026-10-04"
  },
  {
    "slug": "mole-conversions",
    "published": "2026-10-04"
  },
  {
    "slug": "newtons-laws",
    "published": "2026-10-04"
  },
  {
    "slug": "ohms-law",
    "published": "2026-10-04"
  },
  {
    "slug": "passe-compose-etre-verbs",
    "published": "2026-10-04"
  },
  {
    "slug": "periodic-trends",
    "published": "2026-10-04"
  },
  {
    "slug": "photosynthesis-vs-cellular-respiration",
    "published": "2026-10-04"
  },
  {
    "slug": "power-rule-derivatives",
    "published": "2026-10-04"
  },
  {
    "slug": "preterite-vs-imperfect",
    "published": "2026-10-04"
  },
  {
    "slug": "product-rule",
    "published": "2026-10-04"
  },
  {
    "slug": "punnett-squares",
    "published": "2026-10-04"
  },
  {
    "slug": "pythagorean-theorem",
    "published": "2026-10-04"
  },
  {
    "slug": "quadratic-formula",
    "published": "2026-10-04"
  },
  {
    "slug": "semicolons-vs-colons",
    "published": "2026-10-04"
  },
  {
    "slug": "ser-vs-estar",
    "published": "2026-10-04"
  },
  {
    "slug": "slope-and-line-equations",
    "published": "2026-10-04"
  },
  {
    "slug": "sohcahtoa",
    "published": "2026-10-04"
  },
  {
    "slug": "sum-diff-cubes",
    "published": "2026-10-04"
  },
  {
    "slug": "supply-and-demand-shifts",
    "published": "2026-10-04"
  },
  {
    "slug": "transcription-vs-translation",
    "published": "2026-10-04"
  },
  {
    "slug": "z-scores-and-empirical-rule",
    "published": "2026-10-04"
  }
];
