// Generated by scripts/generate-tips.mjs, do not edit.
export const TIPS: { slug: string; published: string }[] = [
  {
    "slug": "comma-splice-fanboys",
    "published": "2026-10-04"
  },
  {
    "slug": "mitosis-vs-meiosis",
    "published": "2026-10-04"
  },
  {
    "slug": "mole-conversions",
    "published": "2026-10-04"
  },
  {
    "slug": "newtons-laws",
    "published": "2026-10-04"
  },
  {
    "slug": "preterite-vs-imperfect",
    "published": "2026-10-04"
  },
  {
    "slug": "quadratic-formula",
    "published": "2026-10-04"
  },
  {
    "slug": "ser-vs-estar",
    "published": "2026-10-04"
  },
  {
    "slug": "sohcahtoa",
    "published": "2026-10-04"
  },
  {
    "slug": "sum-diff-cubes",
    "published": "2026-10-04"
  }
];
